skip estimate_query_size for aggregation and grouping queries
basho/riak_kv pull request #1621
Opened 2017-01-30 15:32 UTC by hmmr

Aggregation and grouping queries don't accumulate data and hence, don't need their size checked against the configured `max_returned_data_size`.

2017-01-30 15:41 UTC, andytill commented on src/riak_kv_qry_worker.erl
> +  when Type /= rows ->
Any reason to not estimate grouped rows? The result can be as big as the full rows.

2017-01-30 15:42 UTC, andytill requested changes

2017-01-30 15:42 UTC, andytill commented on src/riak_kv_qry_worker.erl
> +  when Type /= rows ->
Needs unit tests

2017-01-30 16:23 UTC, DSomogyi commented
create jira issue

2017-01-30 18:58 UTC, hmmr commented on src/riak_kv_qry_worker.erl
> +  when Type /= rows ->
Added one in bb4cd7b.

2017-01-30 18:58 UTC, hmmr commented on src/riak_kv_qry_worker.erl
> +  when Type /= rows ->
Done in 7512632.

2017-01-30 23:21 UTC, hazen reviewed
Tests pass, I'll let you decide if a change is necessary. Probably just a 1-liner and an answer to my question.

2017-01-30 23:21 UTC, javajolt commented on src/riak_kv_qry_worker.erl
> +    BytesPerChunk = CurrentTotalSize / NSubqueriesDone,
Why divide by `NSubqueriesDone` is it's always 1 in the guard?

2017-01-30 23:21 UTC, javajolt commented on src/riak_kv_qry_worker.erl
> +       NSubqueriesDone == 1 ->
Not that familiar with the code, but why are we constraining on `NSubqueriesDone == 1`?  Is that particular to aggregates?

2017-01-31 01:21 UTC, hmmr commented on src/riak_kv_qry_worker.erl
> +       NSubqueriesDone == 1 ->
For `aggregate` queries, the structure in `#state.result` does not grow in size. It is set up initially, at query compilation, with initial states of all groups (columns like `AVG(x)`) which `riak_kv_qry_worker:add_subquery_result`, eventually calling `riak_kv_qry_compiler:run_select`, updates with every collected row.

For `group_by` queries, the result set _does_ grow. A query such as `AVG(x) GROUP BY y` will grow to the number of distinct values in column `y`, which in extreme cases can represent a situation where OOM protection is very much applicable.

d53e0d0 is a properer version of the size checks.

2017-01-31 01:22 UTC, hmmr commented on src/riak_kv_qry_worker.erl
> +    BytesPerChunk = CurrentTotalSize / NSubqueriesDone,
That was me being, you know, too much methodical.

2017-01-31 19:21 UTC, hmmr commented
Docs amended in https://github.com/basho/basho_docs/pull/2415.

2017-02-01 10:50 UTC, andytill approved these changes

2017-02-01 10:50 UTC, andytill commented
+1

2017-02-01 15:39 UTC, javajolt commented
+1

2017-02-01 15:39 UTC, merged